/*
Copyright (c) 2013-2016 Karol M. Stasiak

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
package io.github.karols.units.typelevel

import io.github.karols.units.internal.Bools._
import io.github.karols.units.internal.Integers._

// This trait has only to compile
sealed trait ArithmeticProofs{

	// implicitly[N9 =:= (N9 + _0)]
	// implicitly[N9 =:= (N8 + N1)]
	// implicitly[N9 =:= (N7 + N2)]
	// implicitly[N9 =:= (N6 + N3)]
	// implicitly[N9 =:= (N5 + N4)]
	// implicitly[N9 =:= (N4 + N5)]
	// implicitly[N9 =:= (N3 + N6)]
	// implicitly[N9 =:= (N2 + N7)]
	// implicitly[N9 =:= (N1 + N8)]
	// implicitly[N9 =:= (_0 + N9)]
	// implicitly[N8 =:= (N9 + P1)]
	// implicitly[N8 =:= (N8 + _0)]
	// implicitly[N8 =:= (N7 + N1)]
	// implicitly[N8 =:= (N6 + N2)]
	// implicitly[N8 =:= (N5 + N3)]
	// implicitly[N8 =:= (N4 + N4)]
	// implicitly[N8 =:= (N3 + N5)]
	// implicitly[N8 =:= (N2 + N6)]
	// implicitly[N8 =:= (N1 + N7)]
	// implicitly[N8 =:= (_0 + N8)]
	// implicitly[N8 =:= (P1 + N9)]
	// implicitly[N7 =:= (N9 + P2)]
	// implicitly[N7 =:= (N8 + P1)]
	// implicitly[N7 =:= (N7 + _0)]
	// implicitly[N7 =:= (N6 + N1)]
	// implicitly[N7 =:= (N5 + N2)]
	// implicitly[N7 =:= (N4 + N3)]
	// implicitly[N7 =:= (N3 + N4)]
	// implicitly[N7 =:= (N2 + N5)]
	// implicitly[N7 =:= (N1 + N6)]
	// implicitly[N7 =:= (_0 + N7)]
	// implicitly[N7 =:= (P1 + N8)]
	// implicitly[N7 =:= (P2 + N9)]
	// implicitly[N6 =:= (N9 + P3)]
	// implicitly[N6 =:= (N8 + P2)]
	// implicitly[N6 =:= (N7 + P1)]
	// implicitly[N6 =:= (N6 + _0)]
	// implicitly[N6 =:= (N5 + N1)]
	// implicitly[N6 =:= (N4 + N2)]
	// implicitly[N6 =:= (N3 + N3)]
	// implicitly[N6 =:= (N2 + N4)]
	// implicitly[N6 =:= (N1 + N5)]
	// implicitly[N6 =:= (_0 + N6)]
	// implicitly[N6 =:= (P1 + N7)]
	// implicitly[N6 =:= (P2 + N8)]
	// implicitly[N6 =:= (P3 + N9)]
	// implicitly[N5 =:= (N9 + P4)]
	// implicitly[N5 =:= (N8 + P3)]
	// implicitly[N5 =:= (N7 + P2)]
	// implicitly[N5 =:= (N6 + P1)]
	// implicitly[N5 =:= (N5 + _0)]
	// implicitly[N5 =:= (N4 + N1)]
	// implicitly[N5 =:= (N3 + N2)]
	// implicitly[N5 =:= (N2 + N3)]
	// implicitly[N5 =:= (N1 + N4)]
	// implicitly[N5 =:= (_0 + N5)]
	// implicitly[N5 =:= (P1 + N6)]
	// implicitly[N5 =:= (P2 + N7)]
	// implicitly[N5 =:= (P3 + N8)]
	// implicitly[N5 =:= (P4 + N9)]
	// implicitly[N4 =:= (N9 + P5)]
	// implicitly[N4 =:= (N8 + P4)]
	// implicitly[N4 =:= (N7 + P3)]
	// implicitly[N4 =:= (N6 + P2)]
	// implicitly[N4 =:= (N5 + P1)]
	// implicitly[N4 =:= (N4 + _0)]
	// implicitly[N4 =:= (N3 + N1)]
	// implicitly[N4 =:= (N2 + N2)]
	// implicitly[N4 =:= (N1 + N3)]
	// implicitly[N4 =:= (_0 + N4)]
	// implicitly[N4 =:= (P1 + N5)]
	// implicitly[N4 =:= (P2 + N6)]
	// implicitly[N4 =:= (P3 + N7)]
	// implicitly[N4 =:= (P4 + N8)]
	// implicitly[N4 =:= (P5 + N9)]
	// implicitly[N3 =:= (N9 + P6)]
	// implicitly[N3 =:= (N8 + P5)]
	// implicitly[N3 =:= (N7 + P4)]
	// implicitly[N3 =:= (N6 + P3)]
	// implicitly[N3 =:= (N5 + P2)]
	// implicitly[N3 =:= (N4 + P1)]
	// implicitly[N3 =:= (N3 + _0)]
	// implicitly[N3 =:= (N2 + N1)]
	// implicitly[N3 =:= (N1 + N2)]
	// implicitly[N3 =:= (_0 + N3)]
	// implicitly[N3 =:= (P1 + N4)]
	// implicitly[N3 =:= (P2 + N5)]
	// implicitly[N3 =:= (P3 + N6)]
	// implicitly[N3 =:= (P4 + N7)]
	// implicitly[N3 =:= (P5 + N8)]
	// implicitly[N3 =:= (P6 + N9)]
	// implicitly[N2 =:= (N9 + P7)]
	// implicitly[N2 =:= (N8 + P6)]
	// implicitly[N2 =:= (N7 + P5)]
	// implicitly[N2 =:= (N6 + P4)]
	// implicitly[N2 =:= (N5 + P3)]
	// implicitly[N2 =:= (N4 + P2)]
	// implicitly[N2 =:= (N3 + P1)]
	// implicitly[N2 =:= (N2 + _0)]
	// implicitly[N2 =:= (N1 + N1)]
	// implicitly[N2 =:= (_0 + N2)]
	// implicitly[N2 =:= (P1 + N3)]
	// implicitly[N2 =:= (P2 + N4)]
	// implicitly[N2 =:= (P3 + N5)]
	// implicitly[N2 =:= (P4 + N6)]
	// implicitly[N2 =:= (P5 + N7)]
	// implicitly[N2 =:= (P6 + N8)]
	// implicitly[N2 =:= (P7 + N9)]
	// implicitly[N1 =:= (N9 + P8)]
	// implicitly[N1 =:= (N8 + P7)]
	// implicitly[N1 =:= (N7 + P6)]
	// implicitly[N1 =:= (N6 + P5)]
	// implicitly[N1 =:= (N5 + P4)]
	// implicitly[N1 =:= (N4 + P3)]
	// implicitly[N1 =:= (N3 + P2)]
	// implicitly[N1 =:= (N2 + P1)]
	// implicitly[N1 =:= (N1 + _0)]
	// implicitly[N1 =:= (_0 + N1)]
	// implicitly[N1 =:= (P1 + N2)]
	// implicitly[N1 =:= (P2 + N3)]
	// implicitly[N1 =:= (P3 + N4)]
	// implicitly[N1 =:= (P4 + N5)]
	// implicitly[N1 =:= (P5 + N6)]
	// implicitly[N1 =:= (P6 + N7)]
	// implicitly[N1 =:= (P7 + N8)]
	// implicitly[N1 =:= (P8 + N9)]
	// implicitly[_0 =:= (N9 + P9)]
	// implicitly[_0 =:= (N8 + P8)]
	// implicitly[_0 =:= (N7 + P7)]
	// implicitly[_0 =:= (N6 + P6)]
	// implicitly[_0 =:= (N5 + P5)]
	// implicitly[_0 =:= (N4 + P4)]
	// implicitly[_0 =:= (N3 + P3)]
	// implicitly[_0 =:= (N2 + P2)]
	// implicitly[_0 =:= (N1 + P1)]
	// implicitly[_0 =:= (_0 + _0)]
	// implicitly[_0 =:= (P1 + N1)]
	// implicitly[_0 =:= (P2 + N2)]
	// implicitly[_0 =:= (P3 + N3)]
	// implicitly[_0 =:= (P4 + N4)]
	// implicitly[_0 =:= (P5 + N5)]
	// implicitly[_0 =:= (P6 + N6)]
	// implicitly[_0 =:= (P7 + N7)]
	// implicitly[_0 =:= (P8 + N8)]
	// implicitly[_0 =:= (P9 + N9)]
	// implicitly[P1 =:= (N8 + P9)]
	// implicitly[P1 =:= (N7 + P8)]
	// implicitly[P1 =:= (N6 + P7)]
	// implicitly[P1 =:= (N5 + P6)]
	// implicitly[P1 =:= (N4 + P5)]
	// implicitly[P1 =:= (N3 + P4)]
	// implicitly[P1 =:= (N2 + P3)]
	// implicitly[P1 =:= (N1 + P2)]
	// implicitly[P1 =:= (_0 + P1)]
	// implicitly[P1 =:= (P1 + _0)]
	// implicitly[P1 =:= (P2 + N1)]
	// implicitly[P1 =:= (P3 + N2)]
	// implicitly[P1 =:= (P4 + N3)]
	// implicitly[P1 =:= (P5 + N4)]
	// implicitly[P1 =:= (P6 + N5)]
	// implicitly[P1 =:= (P7 + N6)]
	// implicitly[P1 =:= (P8 + N7)]
	// implicitly[P1 =:= (P9 + N8)]
	// implicitly[P2 =:= (N7 + P9)]
	// implicitly[P2 =:= (N6 + P8)]
	// implicitly[P2 =:= (N5 + P7)]
	// implicitly[P2 =:= (N4 + P6)]
	// implicitly[P2 =:= (N3 + P5)]
	// implicitly[P2 =:= (N2 + P4)]
	// implicitly[P2 =:= (N1 + P3)]
	// implicitly[P2 =:= (_0 + P2)]
	// implicitly[P2 =:= (P1 + P1)]
	// implicitly[P2 =:= (P2 + _0)]
	// implicitly[P2 =:= (P3 + N1)]
	// implicitly[P2 =:= (P4 + N2)]
	// implicitly[P2 =:= (P5 + N3)]
	// implicitly[P2 =:= (P6 + N4)]
	// implicitly[P2 =:= (P7 + N5)]
	// implicitly[P2 =:= (P8 + N6)]
	// implicitly[P2 =:= (P9 + N7)]
	// implicitly[P3 =:= (N6 + P9)]
	// implicitly[P3 =:= (N5 + P8)]
	// implicitly[P3 =:= (N4 + P7)]
	// implicitly[P3 =:= (N3 + P6)]
	// implicitly[P3 =:= (N2 + P5)]
	// implicitly[P3 =:= (N1 + P4)]
	// implicitly[P3 =:= (_0 + P3)]
	// implicitly[P3 =:= (P1 + P2)]
	// implicitly[P3 =:= (P2 + P1)]
	// implicitly[P3 =:= (P3 + _0)]
	// implicitly[P3 =:= (P4 + N1)]
	// implicitly[P3 =:= (P5 + N2)]
	// implicitly[P3 =:= (P6 + N3)]
	// implicitly[P3 =:= (P7 + N4)]
	// implicitly[P3 =:= (P8 + N5)]
	// implicitly[P3 =:= (P9 + N6)]
	// implicitly[P4 =:= (N5 + P9)]
	// implicitly[P4 =:= (N4 + P8)]
	// implicitly[P4 =:= (N3 + P7)]
	// implicitly[P4 =:= (N2 + P6)]
	// implicitly[P4 =:= (N1 + P5)]
	// implicitly[P4 =:= (_0 + P4)]
	// implicitly[P4 =:= (P1 + P3)]
	// implicitly[P4 =:= (P2 + P2)]
	// implicitly[P4 =:= (P3 + P1)]
	// implicitly[P4 =:= (P4 + _0)]
	// implicitly[P4 =:= (P5 + N1)]
	// implicitly[P4 =:= (P6 + N2)]
	// implicitly[P4 =:= (P7 + N3)]
	// implicitly[P4 =:= (P8 + N4)]
	// implicitly[P4 =:= (P9 + N5)]
	// implicitly[P5 =:= (N4 + P9)]
	// implicitly[P5 =:= (N3 + P8)]
	// implicitly[P5 =:= (N2 + P7)]
	// implicitly[P5 =:= (N1 + P6)]
	// implicitly[P5 =:= (_0 + P5)]
	// implicitly[P5 =:= (P1 + P4)]
	// implicitly[P5 =:= (P2 + P3)]
	// implicitly[P5 =:= (P3 + P2)]
	// implicitly[P5 =:= (P4 + P1)]
	// implicitly[P5 =:= (P5 + _0)]
	// implicitly[P5 =:= (P6 + N1)]
	// implicitly[P5 =:= (P7 + N2)]
	// implicitly[P5 =:= (P8 + N3)]
	// implicitly[P5 =:= (P9 + N4)]
	// implicitly[P6 =:= (N3 + P9)]
	// implicitly[P6 =:= (N2 + P8)]
	// implicitly[P6 =:= (N1 + P7)]
	// implicitly[P6 =:= (_0 + P6)]
	// implicitly[P6 =:= (P1 + P5)]
	// implicitly[P6 =:= (P2 + P4)]
	// implicitly[P6 =:= (P3 + P3)]
	// implicitly[P6 =:= (P4 + P2)]
	// implicitly[P6 =:= (P5 + P1)]
	// implicitly[P6 =:= (P6 + _0)]
	// implicitly[P6 =:= (P7 + N1)]
	// implicitly[P6 =:= (P8 + N2)]
	// implicitly[P6 =:= (P9 + N3)]
	// implicitly[P7 =:= (N2 + P9)]
	// implicitly[P7 =:= (N1 + P8)]
	// implicitly[P7 =:= (_0 + P7)]
	// implicitly[P7 =:= (P1 + P6)]
	// implicitly[P7 =:= (P2 + P5)]
	// implicitly[P7 =:= (P3 + P4)]
	// implicitly[P7 =:= (P4 + P3)]
	// implicitly[P7 =:= (P5 + P2)]
	// implicitly[P7 =:= (P6 + P1)]
	// implicitly[P7 =:= (P7 + _0)]
	// implicitly[P7 =:= (P8 + N1)]
	// implicitly[P7 =:= (P9 + N2)]
	// implicitly[P8 =:= (N1 + P9)]
	// implicitly[P8 =:= (_0 + P8)]
	// implicitly[P8 =:= (P1 + P7)]
	// implicitly[P8 =:= (P2 + P6)]
	// implicitly[P8 =:= (P3 + P5)]
	// implicitly[P8 =:= (P4 + P4)]
	// implicitly[P8 =:= (P5 + P3)]
	// implicitly[P8 =:= (P6 + P2)]
	// implicitly[P8 =:= (P7 + P1)]
	// implicitly[P8 =:= (P8 + _0)]
	// implicitly[P8 =:= (P9 + N1)]
	// implicitly[P9 =:= (_0 + P9)]
	// implicitly[P9 =:= (P1 + P8)]
	// implicitly[P9 =:= (P2 + P7)]
	// implicitly[P9 =:= (P3 + P6)]
	// implicitly[P9 =:= (P4 + P5)]
	// implicitly[P9 =:= (P5 + P4)]
	// implicitly[P9 =:= (P6 + P3)]
	// implicitly[P9 =:= (P7 + P2)]
	// implicitly[P9 =:= (P8 + P1)]
	// implicitly[P9 =:= (P9 + _0)]

	// implicitly[N9 =:= (N9 - _0)]
	// implicitly[N9 =:= (N8 - P1)]
	// implicitly[N9 =:= (N7 - P2)]
	// implicitly[N9 =:= (N6 - P3)]
	// implicitly[N9 =:= (N5 - P4)]
	// implicitly[N9 =:= (N4 - P5)]
	// implicitly[N9 =:= (N3 - P6)]
	// implicitly[N9 =:= (N2 - P7)]
	// implicitly[N9 =:= (N1 - P8)]
	// implicitly[N9 =:= (_0 - P9)]
	// implicitly[N8 =:= (N9 - N1)]
	// implicitly[N8 =:= (N8 - _0)]
	// implicitly[N8 =:= (N7 - P1)]
	// implicitly[N8 =:= (N6 - P2)]
	// implicitly[N8 =:= (N5 - P3)]
	// implicitly[N8 =:= (N4 - P4)]
	// implicitly[N8 =:= (N3 - P5)]
	// implicitly[N8 =:= (N2 - P6)]
	// implicitly[N8 =:= (N1 - P7)]
	// implicitly[N8 =:= (_0 - P8)]
	// implicitly[N8 =:= (P1 - P9)]
	// implicitly[N7 =:= (N9 - N2)]
	// implicitly[N7 =:= (N8 - N1)]
	// implicitly[N7 =:= (N7 - _0)]
	// implicitly[N7 =:= (N6 - P1)]
	// implicitly[N7 =:= (N5 - P2)]
	// implicitly[N7 =:= (N4 - P3)]
	// implicitly[N7 =:= (N3 - P4)]
	// implicitly[N7 =:= (N2 - P5)]
	// implicitly[N7 =:= (N1 - P6)]
	// implicitly[N7 =:= (_0 - P7)]
	// implicitly[N7 =:= (P1 - P8)]
	// implicitly[N7 =:= (P2 - P9)]
	// implicitly[N6 =:= (N9 - N3)]
	// implicitly[N6 =:= (N8 - N2)]
	// implicitly[N6 =:= (N7 - N1)]
	// implicitly[N6 =:= (N6 - _0)]
	// implicitly[N6 =:= (N5 - P1)]
	// implicitly[N6 =:= (N4 - P2)]
	// implicitly[N6 =:= (N3 - P3)]
	// implicitly[N6 =:= (N2 - P4)]
	// implicitly[N6 =:= (N1 - P5)]
	// implicitly[N6 =:= (_0 - P6)]
	// implicitly[N6 =:= (P1 - P7)]
	// implicitly[N6 =:= (P2 - P8)]
	// implicitly[N6 =:= (P3 - P9)]
	// implicitly[N5 =:= (N9 - N4)]
	// implicitly[N5 =:= (N8 - N3)]
	// implicitly[N5 =:= (N7 - N2)]
	// implicitly[N5 =:= (N6 - N1)]
	// implicitly[N5 =:= (N5 - _0)]
	// implicitly[N5 =:= (N4 - P1)]
	// implicitly[N5 =:= (N3 - P2)]
	// implicitly[N5 =:= (N2 - P3)]
	// implicitly[N5 =:= (N1 - P4)]
	// implicitly[N5 =:= (_0 - P5)]
	// implicitly[N5 =:= (P1 - P6)]
	// implicitly[N5 =:= (P2 - P7)]
	// implicitly[N5 =:= (P3 - P8)]
	// implicitly[N5 =:= (P4 - P9)]
	// implicitly[N4 =:= (N9 - N5)]
	// implicitly[N4 =:= (N8 - N4)]
	// implicitly[N4 =:= (N7 - N3)]
	// implicitly[N4 =:= (N6 - N2)]
	// implicitly[N4 =:= (N5 - N1)]
	// implicitly[N4 =:= (N4 - _0)]
	// implicitly[N4 =:= (N3 - P1)]
	// implicitly[N4 =:= (N2 - P2)]
	// implicitly[N4 =:= (N1 - P3)]
	// implicitly[N4 =:= (_0 - P4)]
	// implicitly[N4 =:= (P1 - P5)]
	// implicitly[N4 =:= (P2 - P6)]
	// implicitly[N4 =:= (P3 - P7)]
	// implicitly[N4 =:= (P4 - P8)]
	// implicitly[N4 =:= (P5 - P9)]
	// implicitly[N3 =:= (N9 - N6)]
	// implicitly[N3 =:= (N8 - N5)]
	// implicitly[N3 =:= (N7 - N4)]
	// implicitly[N3 =:= (N6 - N3)]
	// implicitly[N3 =:= (N5 - N2)]
	// implicitly[N3 =:= (N4 - N1)]
	// implicitly[N3 =:= (N3 - _0)]
	// implicitly[N3 =:= (N2 - P1)]
	// implicitly[N3 =:= (N1 - P2)]
	// implicitly[N3 =:= (_0 - P3)]
	// implicitly[N3 =:= (P1 - P4)]
	// implicitly[N3 =:= (P2 - P5)]
	// implicitly[N3 =:= (P3 - P6)]
	// implicitly[N3 =:= (P4 - P7)]
	// implicitly[N3 =:= (P5 - P8)]
	// implicitly[N3 =:= (P6 - P9)]
	// implicitly[N2 =:= (N9 - N7)]
	// implicitly[N2 =:= (N8 - N6)]
	// implicitly[N2 =:= (N7 - N5)]
	// implicitly[N2 =:= (N6 - N4)]
	// implicitly[N2 =:= (N5 - N3)]
	// implicitly[N2 =:= (N4 - N2)]
	// implicitly[N2 =:= (N3 - N1)]
	// implicitly[N2 =:= (N2 - _0)]
	// implicitly[N2 =:= (N1 - P1)]
	// implicitly[N2 =:= (_0 - P2)]
	// implicitly[N2 =:= (P1 - P3)]
	// implicitly[N2 =:= (P2 - P4)]
	// implicitly[N2 =:= (P3 - P5)]
	// implicitly[N2 =:= (P4 - P6)]
	// implicitly[N2 =:= (P5 - P7)]
	// implicitly[N2 =:= (P6 - P8)]
	// implicitly[N2 =:= (P7 - P9)]
	// implicitly[N1 =:= (N9 - N8)]
	// implicitly[N1 =:= (N8 - N7)]
	// implicitly[N1 =:= (N7 - N6)]
	// implicitly[N1 =:= (N6 - N5)]
	// implicitly[N1 =:= (N5 - N4)]
	// implicitly[N1 =:= (N4 - N3)]
	// implicitly[N1 =:= (N3 - N2)]
	// implicitly[N1 =:= (N2 - N1)]
	// implicitly[N1 =:= (N1 - _0)]
	// implicitly[N1 =:= (_0 - P1)]
	// implicitly[N1 =:= (P1 - P2)]
	// implicitly[N1 =:= (P2 - P3)]
	// implicitly[N1 =:= (P3 - P4)]
	// implicitly[N1 =:= (P4 - P5)]
	// implicitly[N1 =:= (P5 - P6)]
	// implicitly[N1 =:= (P6 - P7)]
	// implicitly[N1 =:= (P7 - P8)]
	// implicitly[N1 =:= (P8 - P9)]
	// implicitly[_0 =:= (N9 - N9)]
	// implicitly[_0 =:= (N8 - N8)]
	// implicitly[_0 =:= (N7 - N7)]
	// implicitly[_0 =:= (N6 - N6)]
	// implicitly[_0 =:= (N5 - N5)]
	// implicitly[_0 =:= (N4 - N4)]
	// implicitly[_0 =:= (N3 - N3)]
	// implicitly[_0 =:= (N2 - N2)]
	// implicitly[_0 =:= (N1 - N1)]
	// implicitly[_0 =:= (_0 - _0)]
	// implicitly[_0 =:= (P1 - P1)]
	// implicitly[_0 =:= (P2 - P2)]
	// implicitly[_0 =:= (P3 - P3)]
	// implicitly[_0 =:= (P4 - P4)]
	// implicitly[_0 =:= (P5 - P5)]
	// implicitly[_0 =:= (P6 - P6)]
	// implicitly[_0 =:= (P7 - P7)]
	// implicitly[_0 =:= (P8 - P8)]
	// implicitly[_0 =:= (P9 - P9)]
	// implicitly[P1 =:= (N8 - N9)]
	// implicitly[P1 =:= (N7 - N8)]
	// implicitly[P1 =:= (N6 - N7)]
	// implicitly[P1 =:= (N5 - N6)]
	// implicitly[P1 =:= (N4 - N5)]
	// implicitly[P1 =:= (N3 - N4)]
	// implicitly[P1 =:= (N2 - N3)]
	// implicitly[P1 =:= (N1 - N2)]
	// implicitly[P1 =:= (_0 - N1)]
	// implicitly[P1 =:= (P1 - _0)]
	// implicitly[P1 =:= (P2 - P1)]
	// implicitly[P1 =:= (P3 - P2)]
	// implicitly[P1 =:= (P4 - P3)]
	// implicitly[P1 =:= (P5 - P4)]
	// implicitly[P1 =:= (P6 - P5)]
	// implicitly[P1 =:= (P7 - P6)]
	// implicitly[P1 =:= (P8 - P7)]
	// implicitly[P1 =:= (P9 - P8)]
	// implicitly[P2 =:= (N7 - N9)]
	// implicitly[P2 =:= (N6 - N8)]
	// implicitly[P2 =:= (N5 - N7)]
	// implicitly[P2 =:= (N4 - N6)]
	// implicitly[P2 =:= (N3 - N5)]
	// implicitly[P2 =:= (N2 - N4)]
	// implicitly[P2 =:= (N1 - N3)]
	// implicitly[P2 =:= (_0 - N2)]
	// implicitly[P2 =:= (P1 - N1)]
	// implicitly[P2 =:= (P2 - _0)]
	// implicitly[P2 =:= (P3 - P1)]
	// implicitly[P2 =:= (P4 - P2)]
	// implicitly[P2 =:= (P5 - P3)]
	// implicitly[P2 =:= (P6 - P4)]
	// implicitly[P2 =:= (P7 - P5)]
	// implicitly[P2 =:= (P8 - P6)]
	// implicitly[P2 =:= (P9 - P7)]
	// implicitly[P3 =:= (N6 - N9)]
	// implicitly[P3 =:= (N5 - N8)]
	// implicitly[P3 =:= (N4 - N7)]
	// implicitly[P3 =:= (N3 - N6)]
	// implicitly[P3 =:= (N2 - N5)]
	// implicitly[P3 =:= (N1 - N4)]
	// implicitly[P3 =:= (_0 - N3)]
	// implicitly[P3 =:= (P1 - N2)]
	// implicitly[P3 =:= (P2 - N1)]
	// implicitly[P3 =:= (P3 - _0)]
	// implicitly[P3 =:= (P4 - P1)]
	// implicitly[P3 =:= (P5 - P2)]
	// implicitly[P3 =:= (P6 - P3)]
	// implicitly[P3 =:= (P7 - P4)]
	// implicitly[P3 =:= (P8 - P5)]
	// implicitly[P3 =:= (P9 - P6)]
	// implicitly[P4 =:= (N5 - N9)]
	// implicitly[P4 =:= (N4 - N8)]
	// implicitly[P4 =:= (N3 - N7)]
	// implicitly[P4 =:= (N2 - N6)]
	// implicitly[P4 =:= (N1 - N5)]
	// implicitly[P4 =:= (_0 - N4)]
	// implicitly[P4 =:= (P1 - N3)]
	// implicitly[P4 =:= (P2 - N2)]
	// implicitly[P4 =:= (P3 - N1)]
	// implicitly[P4 =:= (P4 - _0)]
	// implicitly[P4 =:= (P5 - P1)]
	// implicitly[P4 =:= (P6 - P2)]
	// implicitly[P4 =:= (P7 - P3)]
	// implicitly[P4 =:= (P8 - P4)]
	// implicitly[P4 =:= (P9 - P5)]
	// implicitly[P5 =:= (N4 - N9)]
	// implicitly[P5 =:= (N3 - N8)]
	// implicitly[P5 =:= (N2 - N7)]
	// implicitly[P5 =:= (N1 - N6)]
	// implicitly[P5 =:= (_0 - N5)]
	// implicitly[P5 =:= (P1 - N4)]
	// implicitly[P5 =:= (P2 - N3)]
	// implicitly[P5 =:= (P3 - N2)]
	// implicitly[P5 =:= (P4 - N1)]
	// implicitly[P5 =:= (P5 - _0)]
	// implicitly[P5 =:= (P6 - P1)]
	// implicitly[P5 =:= (P7 - P2)]
	// implicitly[P5 =:= (P8 - P3)]
	// implicitly[P5 =:= (P9 - P4)]
	// implicitly[P6 =:= (N3 - N9)]
	// implicitly[P6 =:= (N2 - N8)]
	// implicitly[P6 =:= (N1 - N7)]
	// implicitly[P6 =:= (_0 - N6)]
	// implicitly[P6 =:= (P1 - N5)]
	// implicitly[P6 =:= (P2 - N4)]
	// implicitly[P6 =:= (P3 - N3)]
	// implicitly[P6 =:= (P4 - N2)]
	// implicitly[P6 =:= (P5 - N1)]
	// implicitly[P6 =:= (P6 - _0)]
	// implicitly[P6 =:= (P7 - P1)]
	// implicitly[P6 =:= (P8 - P2)]
	// implicitly[P6 =:= (P9 - P3)]
	// implicitly[P7 =:= (N2 - N9)]
	// implicitly[P7 =:= (N1 - N8)]
	// implicitly[P7 =:= (_0 - N7)]
	// implicitly[P7 =:= (P1 - N6)]
	// implicitly[P7 =:= (P2 - N5)]
	// implicitly[P7 =:= (P3 - N4)]
	// implicitly[P7 =:= (P4 - N3)]
	// implicitly[P7 =:= (P5 - N2)]
	// implicitly[P7 =:= (P6 - N1)]
	// implicitly[P7 =:= (P7 - _0)]
	// implicitly[P7 =:= (P8 - P1)]
	// implicitly[P7 =:= (P9 - P2)]
	// implicitly[P8 =:= (N1 - N9)]
	// implicitly[P8 =:= (_0 - N8)]
	// implicitly[P8 =:= (P1 - N7)]
	// implicitly[P8 =:= (P2 - N6)]
	// implicitly[P8 =:= (P3 - N5)]
	// implicitly[P8 =:= (P4 - N4)]
	// implicitly[P8 =:= (P5 - N3)]
	// implicitly[P8 =:= (P6 - N2)]
	// implicitly[P8 =:= (P7 - N1)]
	// implicitly[P8 =:= (P8 - _0)]
	// implicitly[P8 =:= (P9 - P1)]
	// implicitly[P9 =:= (_0 - N9)]
	// implicitly[P9 =:= (P1 - N8)]
	// implicitly[P9 =:= (P2 - N7)]
	// implicitly[P9 =:= (P3 - N6)]
	// implicitly[P9 =:= (P4 - N5)]
	// implicitly[P9 =:= (P5 - N4)]
	// implicitly[P9 =:= (P6 - N3)]
	// implicitly[P9 =:= (P7 - N2)]
	// implicitly[P9 =:= (P8 - N1)]
	// implicitly[P9 =:= (P9 - _0)]

	// implicitly[P9 =:= (N9#Mul[N1])]
	// implicitly[_0 =:= (N9#Mul[_0])]
	// implicitly[N9 =:= (N9#Mul[P1])]
	// implicitly[P8 =:= (N8#Mul[N1])]
	// implicitly[_0 =:= (N8#Mul[_0])]
	// implicitly[N8 =:= (N8#Mul[P1])]
	// implicitly[P7 =:= (N7#Mul[N1])]
	// implicitly[_0 =:= (N7#Mul[_0])]
	// implicitly[N7 =:= (N7#Mul[P1])]
	// implicitly[P6 =:= (N6#Mul[N1])]
	// implicitly[_0 =:= (N6#Mul[_0])]
	// implicitly[N6 =:= (N6#Mul[P1])]
	// implicitly[P5 =:= (N5#Mul[N1])]
	// implicitly[_0 =:= (N5#Mul[_0])]
	// implicitly[N5 =:= (N5#Mul[P1])]
	// implicitly[P8 =:= (N4#Mul[N2])]
	// implicitly[P4 =:= (N4#Mul[N1])]
	// implicitly[_0 =:= (N4#Mul[_0])]
	// implicitly[N4 =:= (N4#Mul[P1])]
	// implicitly[N8 =:= (N4#Mul[P2])]
	// implicitly[P9 =:= (N3#Mul[N3])]
	// implicitly[P6 =:= (N3#Mul[N2])]
	// implicitly[P3 =:= (N3#Mul[N1])]
	// implicitly[_0 =:= (N3#Mul[_0])]
	// implicitly[N3 =:= (N3#Mul[P1])]
	// implicitly[N6 =:= (N3#Mul[P2])]
	// implicitly[N9 =:= (N3#Mul[P3])]
	// implicitly[P8 =:= (N2#Mul[N4])]
	// implicitly[P6 =:= (N2#Mul[N3])]
	// implicitly[P4 =:= (N2#Mul[N2])]
	// implicitly[P2 =:= (N2#Mul[N1])]
	// implicitly[_0 =:= (N2#Mul[_0])]
	// implicitly[N2 =:= (N2#Mul[P1])]
	// implicitly[N4 =:= (N2#Mul[P2])]
	// implicitly[N6 =:= (N2#Mul[P3])]
	// implicitly[N8 =:= (N2#Mul[P4])]
	// implicitly[P9 =:= (N1#Mul[N9])]
	// implicitly[P8 =:= (N1#Mul[N8])]
	// implicitly[P7 =:= (N1#Mul[N7])]
	// implicitly[P6 =:= (N1#Mul[N6])]
	// implicitly[P5 =:= (N1#Mul[N5])]
	// implicitly[P4 =:= (N1#Mul[N4])]
	// implicitly[P3 =:= (N1#Mul[N3])]
	// implicitly[P2 =:= (N1#Mul[N2])]
	// implicitly[P1 =:= (N1#Mul[N1])]
	// implicitly[_0 =:= (N1#Mul[_0])]
	// implicitly[N1 =:= (N1#Mul[P1])]
	// implicitly[N2 =:= (N1#Mul[P2])]
	// implicitly[N3 =:= (N1#Mul[P3])]
	// implicitly[N4 =:= (N1#Mul[P4])]
	// implicitly[N5 =:= (N1#Mul[P5])]
	// implicitly[N6 =:= (N1#Mul[P6])]
	// implicitly[N7 =:= (N1#Mul[P7])]
	// implicitly[N8 =:= (N1#Mul[P8])]
	// implicitly[N9 =:= (N1#Mul[P9])]
	// implicitly[_0 =:= (_0#Mul[N9])]
	// implicitly[_0 =:= (_0#Mul[N8])]
	// implicitly[_0 =:= (_0#Mul[N7])]
	// implicitly[_0 =:= (_0#Mul[N6])]
	// implicitly[_0 =:= (_0#Mul[N5])]
	// implicitly[_0 =:= (_0#Mul[N4])]
	// implicitly[_0 =:= (_0#Mul[N3])]
	// implicitly[_0 =:= (_0#Mul[N2])]
	// implicitly[_0 =:= (_0#Mul[N1])]
	// implicitly[_0 =:= (_0#Mul[_0])]
	// implicitly[_0 =:= (_0#Mul[P1])]
	// implicitly[_0 =:= (_0#Mul[P2])]
	// implicitly[_0 =:= (_0#Mul[P3])]
	// implicitly[_0 =:= (_0#Mul[P4])]
	// implicitly[_0 =:= (_0#Mul[P5])]
	// implicitly[_0 =:= (_0#Mul[P6])]
	// implicitly[_0 =:= (_0#Mul[P7])]
	// implicitly[_0 =:= (_0#Mul[P8])]
	// implicitly[_0 =:= (_0#Mul[P9])]
	// implicitly[N9 =:= (P1#Mul[N9])]
	// implicitly[N8 =:= (P1#Mul[N8])]
	// implicitly[N7 =:= (P1#Mul[N7])]
	// implicitly[N6 =:= (P1#Mul[N6])]
	// implicitly[N5 =:= (P1#Mul[N5])]
	// implicitly[N4 =:= (P1#Mul[N4])]
	// implicitly[N3 =:= (P1#Mul[N3])]
	// implicitly[N2 =:= (P1#Mul[N2])]
	// implicitly[N1 =:= (P1#Mul[N1])]
	// implicitly[_0 =:= (P1#Mul[_0])]
	// implicitly[P1 =:= (P1#Mul[P1])]
	// implicitly[P2 =:= (P1#Mul[P2])]
	// implicitly[P3 =:= (P1#Mul[P3])]
	// implicitly[P4 =:= (P1#Mul[P4])]
	// implicitly[P5 =:= (P1#Mul[P5])]
	// implicitly[P6 =:= (P1#Mul[P6])]
	// implicitly[P7 =:= (P1#Mul[P7])]
	// implicitly[P8 =:= (P1#Mul[P8])]
	// implicitly[P9 =:= (P1#Mul[P9])]
	// implicitly[N8 =:= (P2#Mul[N4])]
	// implicitly[N6 =:= (P2#Mul[N3])]
	// implicitly[N4 =:= (P2#Mul[N2])]
	// implicitly[N2 =:= (P2#Mul[N1])]
	// implicitly[_0 =:= (P2#Mul[_0])]
	// implicitly[P2 =:= (P2#Mul[P1])]
	// implicitly[P4 =:= (P2#Mul[P2])]
	// implicitly[P6 =:= (P2#Mul[P3])]
	// implicitly[P8 =:= (P2#Mul[P4])]
	// implicitly[N9 =:= (P3#Mul[N3])]
	// implicitly[N6 =:= (P3#Mul[N2])]
	// implicitly[N3 =:= (P3#Mul[N1])]
	// implicitly[_0 =:= (P3#Mul[_0])]
	// implicitly[P3 =:= (P3#Mul[P1])]
	// implicitly[P6 =:= (P3#Mul[P2])]
	// implicitly[P9 =:= (P3#Mul[P3])]
	// implicitly[N8 =:= (P4#Mul[N2])]
	// implicitly[N4 =:= (P4#Mul[N1])]
	// implicitly[_0 =:= (P4#Mul[_0])]
	// implicitly[P4 =:= (P4#Mul[P1])]
	// implicitly[P8 =:= (P4#Mul[P2])]
	// implicitly[N5 =:= (P5#Mul[N1])]
	// implicitly[_0 =:= (P5#Mul[_0])]
	// implicitly[P5 =:= (P5#Mul[P1])]
	// implicitly[N6 =:= (P6#Mul[N1])]
	// implicitly[_0 =:= (P6#Mul[_0])]
	// implicitly[P6 =:= (P6#Mul[P1])]
	// implicitly[N7 =:= (P7#Mul[N1])]
	// implicitly[_0 =:= (P7#Mul[_0])]
	// implicitly[P7 =:= (P7#Mul[P1])]
	// implicitly[N8 =:= (P8#Mul[N1])]
	// implicitly[_0 =:= (P8#Mul[_0])]
	// implicitly[P8 =:= (P8#Mul[P1])]
	// implicitly[N9 =:= (P9#Mul[N1])]
	// implicitly[_0 =:= (P9#Mul[_0])]
	// implicitly[P9 =:= (P9#Mul[P1])]
}
